-- Events table schema (extracted from production 2026-03-07)
-- This table stores all website analytics events

CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,           -- 'pageview' | 'click' | 'form_submit'
  page_url TEXT NOT NULL,             -- full URL
  page_path TEXT NOT NULL,            -- path only (e.g. /academy)
  referrer TEXT,                      -- full referrer URL
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  click_url TEXT,                     -- clicked element URL (clicks only)
  click_text TEXT,                    -- clicked element text / form button text
  click_type TEXT,                    -- 'whatsapp' | 'phone' | 'email' | null
  device_type TEXT,                   -- 'desktop' | 'mobile' | 'tablet'
  screen_width INTEGER,
  country TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  session_id TEXT,                    -- anonymous session identifier
  timezone TEXT                       -- visitor timezone
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_events_created_at ON public.events USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_event_type ON public.events USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_events_type_created ON public.events USING btree (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_page_path ON public.events USING btree (page_path);
CREATE INDEX IF NOT EXISTS idx_events_session_id ON public.events USING btree (session_id) WHERE (session_id IS NOT NULL);

-- RLS: allow anonymous inserts (tracking script), deny reads
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
