-- Changelog table for tracking website changes (visible to business partner in dashboard)
-- Created 2026-03-07

CREATE TABLE IF NOT EXISTS public.changelog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  change_type TEXT NOT NULL,           -- 'feat' | 'fix' | 'content' | 'style' | 'copy' | 'refactor' | 'build'
  title TEXT NOT NULL,                 -- Short description (Hebrew)
  description TEXT,                    -- Longer explanation (optional)
  pages_affected TEXT[],               -- Array of page paths affected
  commit_hash TEXT,                    -- Git commit hash (optional)
  author TEXT DEFAULT 'Claude Code',   -- Who made the change
  severity TEXT DEFAULT 'minor'        -- 'major' | 'minor' | 'patch'
);

CREATE INDEX IF NOT EXISTS idx_changelog_created_at ON public.changelog (created_at DESC);

ALTER TABLE public.changelog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_insert_changelog" ON public.changelog
  FOR INSERT TO anon WITH CHECK (true);

-- RPC: get_changelog (password-protected read)
CREATE OR REPLACE FUNCTION public.get_changelog(p_password text DEFAULT NULL, p_limit integer DEFAULT 50)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  stored_hash text;
  result json;
BEGIN
  SELECT value INTO stored_hash FROM public.dashboard_config WHERE key = 'password_hash';
  IF stored_hash IS NULL OR stored_hash != encode(digest(COALESCE(p_password, ''), 'sha256'), 'hex') THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  SELECT json_agg(row_to_json(t)) INTO result FROM (
    SELECT id, created_at, change_type, title, description, pages_affected, commit_hash, author, severity
    FROM public.changelog
    ORDER BY created_at DESC
    LIMIT p_limit
  ) t;

  RETURN COALESCE(result, '[]'::json);
END;
$function$;

-- RPC: add_changelog_entry (for git hooks / automation)
CREATE OR REPLACE FUNCTION public.add_changelog_entry(
  p_change_type text,
  p_title text,
  p_description text DEFAULT NULL,
  p_pages_affected text[] DEFAULT NULL,
  p_commit_hash text DEFAULT NULL,
  p_author text DEFAULT 'Claude Code',
  p_severity text DEFAULT 'minor'
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  result json;
BEGIN
  INSERT INTO public.changelog (change_type, title, description, pages_affected, commit_hash, author, severity)
  VALUES (p_change_type, p_title, p_description, p_pages_affected, p_commit_hash, p_author, p_severity)
  RETURNING row_to_json(changelog.*) INTO result;

  RETURN result;
END;
$function$;
