---
deployment:
  tasks:
    - /bin/cp -Rf focusai-website/dist/. /home/focusaico/public_html/
    # Draft pages - remove from live until ready
    - /bin/rm -rf /home/focusaico/public_html/services/
